Repository Waiviogit/waivio, pull requests merged in 2020-09, with the labels that each got.

#1454 fixed 3138
  src/client/rewards/Proposition/Proposition.js
Labels: fix issues

#1452 Waiv 3111
  src/client/components/Navigation/TopNavigation.js
  src/client/components/QuickPostEditor/QuickPostEditor.js
  src/client/components/Sidebar/SidebarMenu/index.js
  src/client/locales/default.json
  src/client/locales/ru-RU.json
  src/client/locales/uk-UA.json
  src/client/reducers.js
  src/client/rewards/CampaignFooter/CampaignFooter.js
  src/client/rewards/RewardsList/RewardsList.js
  src/client/rewards/RewardsList/RewardsList.less
  src/client/rewards/rewardsActions.js
  src/client/rewards/rewardsReducer.js
  src/common/routes.js
  src/waivioApi/ApiClient.js
  src/waivioApi/config.json
Labels: fix issues

#1460 Waiv 3167,3166
  src/client/object/ObjectFeed/ObjectFeed.js
  src/client/objectCard/ObjectCardView.js
  src/client/rewards/CampaignFooter/CampaignFooter.js
  src/client/rewards/Rewards.js
Labels: fix issues

#1469 WAIV - [3038, 3149, 3177, 3149]
  src/client/app/Sidebar/RightSidebar.js
  src/client/components/Navigation/TopNavigation.js
  src/client/components/Reactions/ReactionsList.js
  src/client/feed/feedActions.js
  src/client/feed/feedReducer.js
  src/client/object/ObjectFeed/ObjectFeed.js
  src/client/post/postsReducer.js
  src/client/vendor/ReduxInfiniteScroll.js
Labels: work in prorgess

#1461 Waiv 2677
  src/client/locales/default.json
  src/client/locales/ru-RU.json
  src/client/locales/uk-UA.json
  src/client/rewards/CampaignFooter/CampaignButtons.js
  src/client/user/userActions.js
Labels: fix issues

#1474 Waiv 3070
  src/client/locales/default.json
  src/client/locales/ru-RU.json
  src/client/object/AppendForm.js
  src/client/object/WobjHistory.js
  src/common/constants/listOfFields.js
  src/waivioApi/ApiClient.js
Labels: fix issues

#1476 Waiv 3184,3185,3186
  src/client/rewards/Create-Edit/CreateRewardForm.js
  src/client/rewards/Proposition/Proposition.js
Labels: fix issues

#1492 Waiv 3199,3198,3191,3205,3000
  src/client/components/Story/StoryFull.js
  src/client/discoverObjects/DiscoverObjectsContent.js
  src/client/object/Catalog/CatalogWrap.js
  src/client/object/ObjectFeed/ObjectFeed.js
  src/client/rewards/CampaignFooter/CampaignFooter.less
  src/client/rewards/CampaignFooter/CommentsMessages.js
  src/client/rewards/Payment/Payment.js
  src/client/rewards/Payment/PaymentTable/PaymentTableRow.js
  src/client/wallet/Transfer.js
Labels: fix issues

#1495 Waiv 3166,3205
  src/client/rewards/CampaignFooter/CampaignFooter.less
  src/client/rewards/Rewards.js
  src/client/steemConnectAPI.js
  src/waivioApi/ApiClient.js
Labels: fix issues

#1497 WAIV-2974
  src/client/Wrapper.js
  src/client/helpers/apiHelpers.js
  src/client/locales/default.json
  src/client/locales/ru-RU.json
  src/client/reducers.js
  src/client/styles/custom.less
  src/client/styles/mixins.less
  src/client/styles/modules/feed-layout.less
  src/client/user/User.js
  src/client/user/UserWallet.js
  src/client/user/UserWallet.less
  src/client/wallet/ClaimReward.js
  src/client/wallet/PowerUpTransactionFrom.js
  src/client/wallet/PowerUpTransactionTo.js
  src/client/wallet/ReceiveTransaction.js
  src/client/wallet/SavingsTransaction.js
  src/client/wallet/TransferTransaction.js
  src/client/wallet/UserWalletTransactions.js
  src/client/wallet/WalletCancelOrder.js
  src/client/wallet/WalletFillOrderTransferred.js
  src/client/wallet/WalletHelper.js
  src/client/wallet/WalletLimitOrder.js
  src/client/wallet/WalletProposalPay.js
  src/client/wallet/WalletTable-nightmode.less
  src/client/wallet/WalletTable.js
  src/client/wallet/WalletTable.less
  src/client/wallet/WalletTableBodyRow.js
  src/client/wallet/WalletTransaction.js
  src/client/wallet/walletActions.js
  src/client/wallet/walletReducer.js
  src/common/routes.js
  src/waivioApi/ApiClient.js
Labels: fix issues

#1499 WAIV-3202, WAIV-3213
  src/client/components/Navigation/MobileNavigation/MobileNavigation.js
  src/client/locales/default.json
  src/client/locales/ru-RU.json
  src/client/notifications/Notifications.less
  src/client/post/PostPreviewModal/PostPreviewModal.less
  src/client/rewards/RewardsList/RewardsList.less
  src/client/rewards/rewardsReducer.js
Labels: fix issues

#1501 Waiv 2473
  src/client/components/Maps/Map.js
  src/client/components/Maps/mapHelper.js
  src/client/object/ObjectFeed/ObjectFeed.less
  src/client/rewards/Proposition/Proposition.js
  src/client/rewards/Rewards.js
  src/waivioApi/ApiClient.js
Labels: fix issues

#1503 WAIV-3216
  src/client/components/EditorExtended/EditorExtended.js
  src/client/components/EditorExtended/components/addbutton.less
  src/client/components/EditorExtended/index.less
  src/client/components/Navigation/Notifications/NotificationChangeStatus.js
  src/client/components/Navigation/Notifications/NotificationTransferVesting.js
  src/client/locales/default.json
  src/client/locales/ru-RU.json
  src/client/object/ObjectOfTypePage/ObjectOfTypePage.js
  src/client/post/EditPost/EditPost.js
  src/client/post/PostPreviewModal/PostPreviewModal.less
  src/client/rewards/Proposition/Proposition.less
  src/client/styles/modules/post-layout.less
Labels: fix issues

#1506 WAIV-3178
  src/client/locales/default.json
  src/client/locales/ru-RU.json
  src/client/object/AppendForm.js
Labels: fix issues

#1512 WAIV-3058
  src/client/components/Story/BodyShort.js
  src/client/locales/default.json
  src/client/object/AppendForm.js
Labels: fix issues

#1524 WAIV-2511
  src/client/app/Sidebar/RightSidebar.js
  src/client/app/Sidebar/UserSidebar.js
  src/client/feed/Feed.js
  src/client/locales/default.json
  src/client/locales/ru-RU.json
  src/client/user/UserDynamicList.js
  src/client/user/UserProfile.js
Labels: fix issues

#1525 WAIV-3209, WAIV-2517, WAIV-2984, WAIV-3233, WAIV-3236
  public/favicon.ico
  src/client/components/EditorExtended/components/addbutton.less
  src/client/components/EditorExtended/components/toolbar-nightmode.less
  src/client/components/EditorExtended/components/toolbar.js
  src/client/components/EditorExtended/components/toolbar.less
  src/client/components/EditorExtended/editor.js
  src/client/locales/default.json
  src/client/locales/ru-RU.json
  src/client/rewards/Reports/Reports-nightmode.less
Labels: fix issues

#1529 WAIV-3234
  src/client/feed/feedActions.js
  src/client/user/UserProfile.js
  src/waivioApi/ApiClient.js
Labels: fix issues

#1538 WAIV-3251
  src/client/components/UserHeader.js
  src/client/components/UserHeader.less
Labels: fix issues

#1549 WAIV-3223
  src/client/components/Navigation/Notifications/NotificationCustomerSupport.js
  src/client/rewards/CampaignFooter/CampaignFooter.js
  src/client/rewards/FilteredRewardsList.js
  src/client/rewards/History/History.js
  src/client/rewards/RewardsBreadcrumb/RewardBreadcrumb.js
  src/client/rewards/rewardsHelper.js
  src/common/routes/routes.js
  src/waivioApi/ApiClient.js
Labels: fix issues

#1555 WAIV-3293
  src/client/components/EditorExtended/components/sides/ImageSideButton.js
  src/client/components/EditorExtended/index.less
  src/client/components/ImageSetter/ImageSetter.js
Labels: fix issues

#1554 waiv3136
  src/client/helpers/wObjectHelper.js
  src/client/object/Catalog/CatalogBreadcrumb/CatalogBreadcrumb-nightmode.less
  src/client/object/Catalog/CatalogBreadcrumb/CatalogBreadcrumb.js
  src/client/object/Catalog/CatalogBreadcrumb/CatalogBreadcrumb.less
  src/client/object/Catalog/CatalogSorting/CatalogSorting.js
  src/client/object/Catalog/CatalogWrap.js
  src/client/object/Catalog/CatalogWrap.less
  src/client/object/ObjectOfTypePage/ObjectOfTypePage.js
  src/client/object/Wobj.js
  src/client/object/styles/custom.less
  src/client/object/styles/modules/variables.less
  src/client/object/wobjActions.js
  src/client/object/wobjectReducer.js
  src/client/reducers.js
Labels: fix issues

#1558 WAIV-2301, WAIV-3283
  src/client/components/EditorExtended/EditorExtended.js
  src/client/components/EditorExtended/components/LinkEditComponent.js
  src/client/components/EditorExtended/components/addbutton.js
  src/client/components/EditorExtended/components/toolbar.less
  src/client/components/EditorExtended/util/editorStateToMarkdown.js
  src/client/helpers/postHelpers.js
  src/client/post/EditPost/EditPost.js
Labels: fix issues

#1561 WAIV-3178
  src/client/locales/default.json
  src/client/object/ObjectGallery/CreateImage.js
Labels: fix issues

#1565 Waiv 3261,3297,3376
  src/client/objectCard/ObjectCardView.js
  src/client/rewards/Details/DetailsBody.js
  src/client/rewards/Payment/Payment.js
  src/client/rewards/Payment/PaymentTable/PaymentTableRow.js
  src/client/rewards/Rewards.js
  src/common/routes/constants.js
Labels: fix issues

#1572 WAIV-3383
  src/client/app/Sidebar/ObjectInfo.js
Labels: fix issues

#1570 Waiv 3000, 3262, 3399
  src/client/components/EditorExtended/EditorExtended.js
  src/client/post/EditPost/EditPost.js
  src/client/rewards/Details/Details.js
  src/client/rewards/Details/DetailsPostRequirments.js
  src/client/rewards/rewardsHelper.js
  src/client/user/userActions.js
Labels: fix issues

#1571 Waiv 3243
  src/client/rewards/Payment/Payment.js
  src/client/wallet/Transfer/Transfer.js
  src/waivioApi/ApiClient.js
Labels: fix issues

#1575 WAIV-3316
  src/client/object/Catalog/AddItemModal/AddItemModal.js
  src/client/object/Catalog/CatalogWrap.js
  src/client/post/CreateObjectModal/CreateObject.js
Labels: issues
